# Site settings
title: "Katie and Steven"
description: |
    Greenbush, Minnesota

    June 15, 2019
owner: Steven Hlucny
first_published: 2018
email:
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.katieandsteven.net" # the base hostname & protocol for your site

social:
  github: https://github.com/sdhlucny/wedding-site

# Build settings
markdown: kramdown
